routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/products', 'FrontController@products')->name('products');

Route::get('/category/{id}', 'FrontController@show')->name('category');

Route::get('/product/{id}', 'FrontController@product')->name('product');

Route::group(['prefix' => 'admin', 'middleware'=>'auth'], function() {
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');

    Route::resource('product', 'ProductsController');
    Route::resource('category', 'CategoriesController');
    Route::resource('user', 'UsersController');
});

Route::get('/', 'FrontController@index')->name('main');

Route::resource('/cart', 'CartController');

Route::group(['middleware' => ['web']], function () {

    Route::get('/comments/{id}', 'FrontController@showComments')->name('comments');

});

app/Http/Controllers/FrontController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Category;

use App\Post;
use App\Http\Requests;


class FrontController extends Controller
{
    public function index()
    {
        $products=Product::all();
        return view('front.home', compact('items'));
    }

    public function products()
    {
        $categories=Category::all();
        $products=Product::all();
        return view('front.products', compact('products', 'categories'));
    }

    public function product($id)
    {
        $product=Product::find($id);
        return view('front.product', compact('product'));
    }

    public function show($id)
    {
        $products=Category::find($id)->products;

        $categories=Category::all();

        return view('front.products',compact(['categories','products']));
    }

    protected $posts_per_page = 10;

    public function showComments(Request $request, $id) {

        $posts = Post::paginate($this->posts_per_page);

        if($request->ajax()) {
            return [
                'posts' => view('front.ajax.index')->with(compact('posts'))->render(),
                'next_page' => $posts->nextPageUrl()
            ];
        }

        return view('front.comments')->with(compact('posts'));

    }

    public function fetchNextPostsSet($page) {



    }

}

resources/views/front/comments.blade.php
@extends('layout.main')

@section('content')

    <section class="posts endless-pagination" data-next-page="{{ $posts->nextPageUrl() }}">
        @foreach($posts as $post)

            <div class="article">
                <h2>{{ $post->title }}</h2>
                {{ $post->content }}
            </div>

        @endforeach

    </section>
    <script>

        $(document).ready(function() {
            $(window).scroll(fetchPosts);

            function fetchPosts() {

                var page = $('.endless-pagination').data('next-page');

                if(page !== null) {

                    clearTimeout( $.data( this, "scrollCheck" ) );

                    $.data( this, "scrollCheck", setTimeout(function() {
                        var scroll_position_for_posts_load = $(window).height() + $(window).scrollTop() + 100;

                        if(scroll_position_for_posts_load >= $(document).height()) {
                            $.get(page, function(data){
                                $('.posts').append(data.posts);
                                $('.endless-pagination').data('next-page', data.next_page);
                            });
                        }
                    }, 350))

                }
            }


        })

    </script>
@stop

resources/views/front/product.blade.php
@extends('layout.main')

@section('content')

    <div class="row">
        <div class="small-5 small-offset-1 columns">
            <div class="item-wrapper">
                <div class="img-wrapper">
                    <a href="#">
                        <img src="{{url('images', $product->image)}}"/>
                    </a>
                </div>
            </div>
        </div>
        <div class="small-6 columns">
            <div class="row">
                <div class="large-12 columns">
                    <h2>
                        {{$product->title}}
                    </h2>
                </div>
            </div>
            <div class="item-wrapper">
                <h3 class="subheader">
                    <span class="price-tag">${{$product->price}}</span>
                </h3>
                <div class="row">
                    <div class="large-12 columns">
                        <p>
                            {{$product->description}}
                        </p>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="large-12 columns">
                        <a href="{{route('cart.edit', $product->id)}}" class="button  expanded">Add to Cart</a>
                    </div>
                </div>
                <div class="row">
                    <div class="large-12 columns">
                        <a href="{{route('comments', $product->id)}}" class="button  expanded">Show comments</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/front/products.blade.php
@extends('layout.main')

@section('content')
    <div class="row">
        <div class="col-sm-6">
            <div class="sidebar content-box">
                @if(!empty($categories))
                        <ul class="nav">
                            <h6>Categories</h6>
                            @forelse($categories as $category)
                            <li><a href="{{route('category', $category->id)}}">{{$category->title}}</a></li>
                            @empty
                                <h3>No items</h3>
                        </ul>
                    @endforelse
                @endif
            </div>
        </div>
        <div class="col-sm-6">
            <div class="row">
                @forelse($products as $product)
                    <div class="small-3 columns">
                        <div class="item-wrapper">
                            <div class="img-wrapper">
                                <a class="button expanded add-to-cart" href="{{route('cart.edit', $product->id)}}">
                                    Add to Cart
                                </a>
                                <a href="#">
                                    <img src="{{url('images', $product->image)}}"/>
                                </a>
                            </div>
                            <a href="{{route('product', $product->id)}}">
                                <h3>
                                    {{$product->title}}
                                </h3>
                            </a>
                            <h5>
                                ${{$product->price}}
                            </h5>
                            <p>
                                {{$product->description}}
                            </p>
                        </div>
                    </div>
                @empty
                    <h3>No products</h3>
                @endforelse
            </div>
        </div>
    </div>
@endsection