routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/products', 'FrontController@products')->name('products');

Route::get('/category/{id}', 'FrontController@show')->name('category');

Route::get('/product/{id}', 'FrontController@product')->name('product');

Route::group(['prefix' => 'admin', 'middleware'=>'auth'], function() {
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');

    Route::resource('product', 'ProductsController');
    Route::resource('category', 'CategoriesController');
    Route::resource('user', 'UsersController');
});

Route::get('/', 'FrontController@index')->name('main');

Route::resource('/cart', 'CartController');

Route::group(['middleware' => ['web']], function () {

    Route::get('/comments/{id}', 'FrontController@showComments')->name('comments');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    protected $fillable=['title', 'description', 'price', 'category_id', 'image'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\Product;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('admin.product.index',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::pluck('title', 'id');
        return view('admin.product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $formInput=$request->except('image');

        $this->validate($request, [
            'title'=>'required',
            'description'=>'required',
            'price'=>'required',
        ]);

        $image=$request->image;
        if($image) {
            $imageName=$image->getClientOriginalName();
            $image->move('images', $imageName);
            $formInput['image']=$imageName;
        }
        Product::create($formInput);
        return redirect()->route('admin.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product=Product::find($id);
        $categories=Category::pluck('title','id');
        return view('admin.product.edit',compact(['product','categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product=Product::find($id);
        $formInput=$request->except('image');
        $this->validate($request,[
            'title'=>'required',
            'description'=>'required',
            'price'=>'required'
        ]);

        $image=$request->image;
        if($image){
            $imageName=$image->getClientOriginalName();
            $image->move('images',$imageName);
            $formInput['image']=$imageName;
        }
        $product->update($formInput);
        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);
        return redirect()->route('product.index');
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layout.admin')

@section('content')

    <h3>Add product</h3>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {!! Form::open(['route'=>'product.store', 'method'=>'post', 'files'=>true]) !!}
            <div class="form-group">
                {{ Form::label('title', 'Title') }}
                {{ Form::text('title', null, array('class'=>'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('description', 'Description') }}
                {{ Form::text('description', null, array('class'=>'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('price', 'Price') }}
                {{ Form::text('price', null, array('class'=>'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('image', 'Image') }}
                {{ Form::file('image', array('class'=>'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('category_id', 'Category') }}
                {{ Form::select('category_id', $categories, null, ['class'=>'form-control']) }}
            </div>

            {{ Form::submit('Create', array('class' => 'btn btn-default'))}}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layout.admin')

@section('content')

    <h3>Edit product</h3>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {!! Form::open(['route'=>['product.update', $product->id], 'method'=>'PUT', 'files'=>true]) !!}
            <div class="form-group">
                {{ Form::label('title', 'Title') }}
                {{ Form::text('title', $product->title, array('class'=>'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('description', 'Description') }}
                {{ Form::text('description', $product->description, array('class'=>'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('price', 'Price') }}
                {{ Form::text('price', $product->price, array('class'=>'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('image', 'Image') }}
                {{ Form::file('image', array('class'=>'form-control')) }}
            </div>

            <div class="form-group">
                {{ Form::label('category_id', 'Category') }}
                {{ Form::select('category_id', $categories, null, ['class'=>'form-control']) }}
            </div>

            {{ Form::submit('Edit', array('class' => 'btn btn-default'))}}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layout.admin')

@section('content')
    <h3>Products</h3>
    <a href="{{route('product.create')}}">Add Product</a>
    <table class="table table-striped">
        <thead>
        <tr>
            <td>ID</td>
            <td>Title</td>
            <td>Description</td>
            <td>Price</td>
            <td>Category</td>
            <td>Image</td>
            <td colspan="2">Action</td>
        </tr>
        </thead>
        <tbody>
        @forelse($products as $product)
            <tr>
                <td>{{$product->id}}</td>
                <td>{{$product->title}}</td>
                <td>{{$product->description}}</td>
                <td>{{$product->price}}</td>
                <td>{{$product->category->title}}</td>
                <td><img src="{{url('images', $product->image)}}"/></td>
                <td><a href="{{ route('product.edit',$product->id)}}" class="btn btn-primary">Edit</a></td>
                <td>
                    <form action="{{ route('product.destroy', $product->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        @empty
            <h3>No products</h3>
        @endforelse
        </tbody>
    </table>
@endsection