routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/products', 'FrontController@products')->name('products');

Route::get('/category/{id}', 'FrontController@show')->name('category');

Route::get('/product/{id}', 'FrontController@product')->name('product');

Route::group(['prefix' => 'admin', 'middleware'=>'auth'], function() {
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin.index');

    Route::resource('product', 'ProductsController');
    Route::resource('category', 'CategoriesController');
    Route::resource('user', 'UsersController');
});

Route::get('/', 'FrontController@index')->name('main');

Route::resource('/cart', 'CartController');

Route::group(['middleware' => ['web']], function () {

    Route::get('/comments/{id}', 'FrontController@showComments')->name('comments');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstName', 'secondName', 'city', 'street', 'houseNumber', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hasRole($roleName)
    {
        return $this->role == $roleName; // sample implementation only
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users=User::all();
        return view('admin.user.index', compact(['users']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user=User::find($id);
        return view('admin.user.edit',compact(['user']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user=User::find($id);


        $user->role = $request->get('role');
        $user->save();
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user=User::find($id);
        $user->delete();
        return redirect()->route('user.index');
    }
}

resources/views/admin/user/edit.blade.php
@extends('admin.layout.admin')

@section('content')

    <h3>Edit user</h3>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {!! Form::open(['route'=>['user.update', $user->id], 'method'=>'PUT', 'files'=>true]) !!}
                <div class="form-group">
                    {{ Form::label('role', 'Role:') }}
                    {{ Form::label('role', 'User') }}
                    {{ Form::radio('role', 'user' , true) }}
                    {{ Form::label('role', 'Admin') }}
                    {{ Form::radio('role', 'admin' , false) }}
                </div>

            {{ Form::submit('Edit', array('class' => 'btn btn-default'))}}
            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layout.admin')

@section('content')
    <h3>Users</h3>
    <table class="table table-striped">
        <thead>
        <tr>
            <td>ID</td>
            <td>E-mail</td>
            <td>Role</td>
            <td colspan="2">Action</td>
        </tr>
        </thead>
        <tbody>
        @forelse($users as $user)
            <tr>
                <td>{{$user->id}}</td>
                <td>{{$user->email}}</td>
                <td>{{$user->role}}</td>
                <td><a href="{{ route('user.edit',$user->id)}}" class="btn btn-primary">Edit</a></td>
                <td>
                    <form action="{{ route('user.destroy', $user->id)}}" method="post">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        @empty
            <h3>No users</h3>
        @endforelse
        </tbody>
    </table>
@endsection